#!/usr/bin/env bash
# This Bash script performs a ping to the specified IP address provided as an argument. Requirements:
#+ Accepts a string representing an IP address as a command-line argument
#+ Displays 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}' if no argument is provided
#+ Conducts a ping operation to the specified IP address five times if an argument is provided

if [ "$#" -eq 0 ]; then
   echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
   ping -c 5 "$1"
fi
