#!/usr/bin/env bash
# this debugs to find out why the serve is not listen on port 80
# and configures nginx to run on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
